### ISSUE TITLE
wrong-type-argument  stringp ,toolbox-tramp-method)

### ISSUE THREAD

**Issue by ghost** [fejfighter/toolbox-tramp#1]
I get this error when trying to connect to toolbox. 

Steps to reproduce:
1. `emacs -Q`
2. Eval toolbox-tramp.el
3. Try to open a file in toolbox `/toolbox::/home/[user]/.emacs.d/init.el`

Emacs version: `"GNU Emacs 28.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4)
 of 2022-02-24"`

Available containers: `((nil "fedora-toolbox-34") (nil "fedora-toolbox-35"))`

Backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument stringp ,toolbox-tramp-method)
  tramp-find-host("toolbox" nil nil)
  tramp-dissect-file-name("/toolbox::/home/[user]/.emacs.d/init.el")
  tramp-file-name-handler(substitute-in-file-name "/toolbox::/home/[user]/.emacs.d/init.el")
  substitute-in-file-name("~//toolbox::/home/[user]/.emacs.d/init.el")
  completion--file-name-table("~//toolbox::/home/[user]/.emacs.d/init.el" file-exists-p lambda)
  complete-with-action(lambda completion--file-name-table "~//toolbox::/home/[user]/.emacs.d/init.el" file-exists-p)
  #f(compiled-function (table) #<bytecode -0x1f60d3c0325ece15>)(completion--file-name-table)
  completion--some(#f(compiled-function (table) #<bytecode -0x1f60d3c0325ece15>) (completion--embedded-envvar-table completion--file-name-table))
  read-file-name-internal("~//toolbox::/home/[user]/.emacs.d/init.el" file-exists-p lambda)
  completion--complete-and-exit(12 50 exit-minibuffer #f(compiled-function () #<bytecode -0xae183e0846db2c9>))
  completion-complete-and-exit(12 50 exit-minibuffer)
  minibuffer-complete-and-exit()
  funcall-interactively(minibuffer-complete-and-exit)
  command-execute(minibuffer-complete-and-exit)
  completing-read-default("Find file: " read-file-name-internal file-exists-p confirm-after-completion "~/" file-name-history "~/" nil)
  read-file-name-default("Find file: " nil "~/" confirm-after-completion nil nil)
  read-file-name("Find file: " nil "~/" confirm-after-completion)
  find-file-read-args("Find file: " confirm-after-completion)
  byte-code("\300\301\302 \"\207" [find-file-read-args "Find file: " confirm-nonexistent-file-or-buffer] 3)
  command-execute(find-file)
```

**Comment by fejfighter** [comment]
Hi @dm19 

Is this (emacs) build from source? If so, what is the commit? ( can you pull the newer tramp changes from the last week or so?)

I have been unable to reproduce with the tagged versions from the emacs repo.

I was previously getting this issue so is this definitely the latest version of toolbox-tramp? 
I don't need to worry about bytecode files, as we are eval-ing the file 

i'm not sure what else this could be right now

**Comment by ghost** [comment]
@fejfighter I'm so sorry, this was a fresh install of emacs so I thought I had the latest version of toolbox-tramp, but apparently not. Pulled it again and it seems to be working.
