### ISSUE TITLE
Merge into emacs master?

### ISSUE THREAD

**Issue by maddovr** [fejfighter/toolbox-tramp#3]
Emacs has recently added support for docker as a tramp backend, maybe you could push for toolbox/podman as well? I think most of the current code could be reused, maybe adding a small variable?

**Comment by fejfighter** [comment]
Once I saw the addition of tramp docker I was considering a move to merge both options.

I have been away but I will aim to look into the details this week.

**Comment by fejfighter** [comment]
Something like this was merged in today. I'm not sure if master or emacs-29

alternatively using latest tramp from a package should have the same code - closing this ticket

I will likely lean on the container mode here a little more

**Comment by alternateved** [comment]
FYI it was merged on master only: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=0be40fbe43c4e409a417b12d2919ca64326e0281
